go_library(
    name = "enrichment",
    srcs = [
        "issue.go",
    ],
    visibility = ["//cmd/enricher"],
    deps = [
        "//pkg/enrichment/db",
        "//api/proto:dracon",
        "//third_party/go:protobuf",
    ],
)
