proto_library(
    name = "dracon",
    srcs = [
        "engine.proto",
        "issue.proto",
    ],
    languages = [
        "go",
        "py",
    ],
    visibility = ["PUBLIC"],
    deps = ["//third_party/proto:protoc"],
)
