go_library(
    name = "consumers",
    srcs = [
        "consumer.go",
    ],
    visibility = ["//consumers/..."],
    deps = [
        "//pkg/genproto/v1",
        "//pkg/putil",
        "//third_party/go:gogo_protobuf",
        "//third_party/go:golang_protobuf",
    ],
)
