FROM python:3.7-alpine

RUN adduser --shell /bin/false -u 1000 -D app
RUN pip3 install bandit

COPY --chown=app:app . /home/app/dracon/


USER app
ENV PYTHONPATH=$PYTHONPATH:/home/app/dracon
ENTRYPOINT ["python3 /home/app/dracon/producers/python_bandit/python_bandit.py"]
