FROM python:3.7-alpine
RUN adduser --shell /bin/false -u 1000 -D app

USER app
COPY --chown=app:app enrichment_service/enrichment-service.py /home/app

ENTRYPOINT ["python3","/home/app/enrichment-service.py"]
 