FROM python:3.7-alpine
RUN adduser --shell /bin/false -u 1000 -D app
COPY --chown=app:app . /home/app/dracon

WORKDIR /home/app/dracon/
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev &&\
    pip3 install protobuf google psycopg2-binary

USER app
ENV PYTHONPATH=$PYTHONPATH:/home/app/dracon
ENTRYPOINT ["python3","/home/app/dracon/enrichment_service/enrichment_service.py"]
 