go_library(
    name = "putil",
    srcs = [
        "load.go",
        "write.go",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third_party/go:gogo_protobuf",
        "//third_party/go:pkg_errors",
        "//api/proto:dracon",
    ],
)
