go_binary(
    name = "enricher",
    srcs = [
        "main.go",
    ],
    deps = [
        "//pkg/enrichment",
        "//pkg/enrichment/db",
        "//pkg/genproto/v1",
        "//pkg/putil",
        "//third_party/go:spf13_cobra",
        "//third_party/go:spf13_viper",
    ],
)
